head:
  css:
    fonts: https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@900&display=swap
  js:
    async: https://cdn.jsdelivr.net/npm/ionicons/dist/ionicons.js


mode: time
# å¯é€‰ light | dark | auto | time

favicon: /images/favicon.svg

avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: å»ºæ¨¡å»ºæ¨¡å‘œå‘œå‘œï¼

bg_image:
  enable: true
  url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0-blur-30px.jpg
  dark: /images/asuka.png
  blur: 10px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

sidebar:
  bg_image: /images/button.jpg
  bg_position: bottom 3rem center
fireworks:
  enable: true
  colors:
    - "#00D1CE"
    - "#66D6FF"
    - "#919191"

colors:
  primary: "#66d6ff"
  # bg: "#F5F5F5"
  selection_bg: "#8cacdd" # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

font:
  cdn:
    pre: 'https://cdn.jsdelivr.net/gh/Anduin9527/Anduin9527.github.io@latest'
    css:
    js:
      base:
       - xxx
      async:
        # é»˜è®¤å¼•å…¥çš„å›¾æ ‡èµ„æºï¼Œä½¿ç”¨ iconfont
        iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js
      defer:

  serif:
    family: "'Songti SC', 'Noto Serif SC', STZhongsong, STKaiti, KaiTi, Roboto, serif"
    weight: 900
  sans_serif:
    family: "'PingFang SC', 'Microsoft YaHei', Roboto, Arial, sans-serif"
    weight: 400
  monospace:
    family: "'Source Code Pro', 'Courier New', Courier, Consolas, Monaco, monospace"

reward:
  enable: false
  comment: ä¸å–å’–å•¡çœŸçš„éš¾é¡¶

comment:
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿ä¸æˆ‘äº¤æµã€‚

waline:
  enable: false
  serverURL: https://waline.yunyoujun.cn
  visitor: false
  comment: false
  avatarCDN: https://cdn.v2ex.com/gravatar/
  placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredFields: ["nick"]

github_issues:
  enable: false

github_discussions:
  enable: false

social:
  - name: QQ
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: tencent://message/?uin=2676057183&Site=&Menu=yes
    icon: ri:qq-line
    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/Anduin9527
    icon: ri:github-line
    color: "#181717"
  - name: E-Mail
    link: mailto:2676057183@qq.com
    icon: ri:mail-line
    color: "#8E71C1"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=579015212
    icon: ri:netease-cloud-music-line
    color: "#C10D0C"
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/chu-liu-16-64
    icon: ri:zhihu-line
    color: "#0084FF"
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/21994551
    icon: ri:bilibili-line
    color: "#FF8EB3"
  - name: RSS
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange

banner:
  enable: true
  title:
    - æ‹‰æ™®
    - æ‹‰æ–¯~
    - çš„
    - ä¹–ç¦»å™¨
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

disqusjs:
  enable: false
  shortname: yunyoujun
  apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

footer:
  since: 2020
  enable: true
  icon:
    enable: false
  beian:
    enable: true
    icp: é—½ICPå¤‡2021012704å·
  support:
    enable: false
    title: åˆæ‹äº‘
    link: https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral
    logo: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾› CDN åŠ é€Ÿ
  powered:
    enable: true
  custom_text:


engine_search:
  enable: true
  href: "https://www.google.com/search?q=site:"
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: lapras.xyz

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia
algolia_search:
  enable: false
  # ...

google_analytics:
  enable: true
  id: G-NSLVQ2H5JH

baidu_push: true

google_adsense:
  enable: false
  client: ca-pub-2245427233262012

post_card:
  opacity: 0.8

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true
toc:
  list_number: false
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•
  collapse: false

post_edit:
  enable: false
  url: https://github.com/YunYouJun/yunyoujun.github.io/tree/hexo/source/

codeblock:
  copy_btn: true
  prismjs:
    light: tomorrow
    dark: tomorrow

katex:
  copy_tex: false
  global: false

albums:
  enable: false

girls:
  enable: false

tags:
  æ•°å­¦: "#114514"
  å›å½’åˆ†æ: "#191981"
  åŠ¨ç”»: crimson
  #Parcel: "#21374b"
  ç¡¬ä»¶: "#ecf0f1"
  æ•™ç¨‹: royalblue
  ç¬”è®°: dimgray
  åˆ†äº«: "#0078e7"
  éšç¬”: mediumpurple
  ç®—æ³•: "#d04d2d"
  ç½‘ç»œ: "#1cafdb"
  Linux: "#2577b1"
  æ•°æ®ç»“æ„: "#ccb44b"
  æ ‘: "#31b95e"
  æ¸¸æˆ: midnightblue
  Vue: "#4fc08d"
  Hexo: "#0E834D"
  CSS: "#5298d1"
  Node.js: "#026E00"
  Git: "#F14E32"
  React: "#61dafb"
  Python: "#3776ab"
  SPSS: "#448444"
  PHP: "#8892BF"
  VS Code: "#0066B8"
  JavaScript: "#F4DF4F"
  TypeScript: "#317AC6"
  Laravel: "#F4645F"
  C: crimson
  C++: saddlebrown
  è®¡ç®—æœºå›¾å½¢å­¦: "#006432"
  å½¢å¼è¯­è¨€: "#d892e4"

categories:
  é¡¹ç›®ç»å†: "#4ba700"
  ç®—æ³•å­¦ä¹ : "#317ec7"
  æ•´æ´»: "#f3c9f9"
  æŠ˜è…¾ç³»åˆ—: "#e67e22"
  æ•°å­¦å»ºæ¨¡: "#123f81"
  è®¡ç®—æœºç»„æˆåŸç†: "#736e30"
  æ±‡ç¼–è¯­è¨€ç¨‹åºè®¾è®¡: "##beedff"
  ç¼–è¯‘åŸç†: "#a000e4"
  çˆ¬è™«å­¦ä¹ : "#eeff54"
  Games101ç¬”è®°: "#f1e500"

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
  - name: æˆ‘æ°¸è¿œå–œæ¬¢oo
    url: /girls/
    icon: ri:women-line
    color: hotpink

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line

archive:
  last_word: æ²¡æœ‰æ›´å¤šçš„é»‘å†å²äº†_(:Ğ·ã€âˆ )_

cursor:
  enable: true

google_tagmanager:
  enable: false
  id: GTM-M9KWR9L

wordcount:
  enable: true
  count: true
  time: true

say:
  enable: false
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

notice:
  enable: true
  content: Fus-ro-dah!

wordcloud:
  enable: true
  height: 350 

mourn:
  enable: true
  days:
    - "4-4"
    - "5-12"
    - "12-13"
mermaid:
  enable: true
  options: # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    startOnload: true # default true
  global: true # default true
  

